#!/bin/bash

GRN='\033[0;32m'
RED='\033[0;31m'
BLU='\033[1;34m'
NC='\033[0m'
A='\033[0;34m'
B='\033[0;31m'
C='\033[0;32m'
D='\033[0;33m'
E='\033[0;34m'
F='\033[0;35m'
G='\033[0;36m'
H='\033[0;28m'
I='\033[2;33m'
J='\033[3;31m'


if [[ $EUID -ne 0 ]];
then
	echo -e " [${RED}!${NC}] I cannot be run as mortal. Try again as root"
	exit 1
fi

echo -e " [${GRN}+${NC}] set ssh banner"
echo -e "This is a private server.
If you are not allow to access to it, you should disconnect

/!\ All connections are monitored and recorded /!\
" > /etc/motd
sed -i 's/PrintLastLog yes/PrintLastLog no/g' /etc/ssh/sshd_config
