#!/bin/bash

GRN='\033[0;32m'
RED='\033[0;31m'
BLU='\033[1;34m'
NC='\033[0m'


if [[ $EUID -ne 0 ]];
then
	echo -e " [${RED}!${NC}] I cannot be run as mortal. Try again as root"
	exit 1
fi

echo -e " [${GRN}+${NC}] updating your system"
apt-get -qq update  2>&1 >&/dev/null
echo -e " [${GRN}+${NC}] upgrading your system"
apt-get -qq upgrade -yy 2>&1 >&/dev/null
echo -e " [${GRN}+${NC}] installation of
     sudo  |  git  |  htop
     wget  |  curl |  emacs"
apt-get install sudo git htop wget curl emacs -yy 2>&1 >&/dev/null
