#!/bin/bash

GRN='\033[0;32m'
RED='\033[0;31m'
BLU='\033[1;34m'
NC='\033[0m'


if [[ $EUID -ne 0 ]];
then
	echo -e " [${RED}!${NC}] I cannot be run as mortal. Try again as root"
	exit 1
fi


echo -e " [${GRN}+${NC}] change permissions for few commands :
     gcc*     | make    | apt-get
     aptitude | dpkg*   | fail2ban
     netstat  | crontab | curl
     wget     | locate  | logger
     ifconfig | sysctl"
chmod o-x /usr/bin/gcc* 2>&-
chmod o-x /usr/bin/make 2>&-
chmod o-x /usr/bin/apt-get 2>&-
chmod o-x /usr/bin/aptitude 2>&-
chmod o-x /usr/bin/dpkg* 2>&-
chmod o-x /usr/bin/fail2ban* 2>&-
chmod o-x /bin/netstat 2>&-
chmod o-x /usr/bin/crontab 2>&-
chmod o-x /usr/bin/curl 2>&-
chmod o-x /usr/bin/wget 2>&-
chmod o-x /usr/bin/locate 2>&-
chmod o-x /usr/bin/logger 2>&-
chmod o-x /usr/bin/rkhunter 2>&-
chmod o-x /sbin/ifconfig 2>&-
chmod o-x /sbin/sysctl 2>&-
