#!/bin/bash

GRN='\033[0;32m'
RED='\033[0;31m'
BLU='\033[1;34m'
NC='\033[0m'
A='\033[0;34m'
B='\033[0;31m'
C='\033[0;32m'
D='\033[0;33m'
E='\033[0;34m'
F='\033[0;35m'
G='\033[0;36m'
H='\033[0;28m'
I='\033[2;33m'
J='\033[3;31m'


if [[ $EUID -ne 0 ]];
then
	echo -e " [${RED}!${NC}] I cannot be run as mortal. Try again as root"
	exit 1
fi


echo -e " [${GRN}+${NC}] change permissions for few commands :
     gcc* | make | apt-get | aptitude | dpkg* | fail2ban | netstat |
     crontab | curl | wget | locate | logger"
chmod o-x /usr/bin/gcc* 2>&-
chmod o-x /usr/bin/make 2>&-
chmod o-x /usr/bin/apt-get 2>&-
chmod o-x /usr/bin/aptitude 2>&-
chmod o-x /usr/bin/dpkg* 2>&-
chmod o-x /usr/bin/fail2ban* 2>&-
chmod o-x /bin/netstat 2>&-
chmod o-x /usr/bin/crontab 2>&-
chmod o-x /usr/bin/curl 2>&-
chmod o-x /usr/bin/wget 2>&-
chmod o-x /usr/bin/locate 2>&-
chmod o-x /usr/bin/logger 2>&-
chmod o-x /usr/bin/rkhunter 2>&-
