#!/bin/bash

GRN='\033[0;32m'
RED='\033[0;31m'
BLU='\033[1;34m'
NC='\033[0m'


if [[ $EUID -ne 0 ]];
then
	echo -e " [${RED}!${NC}] I cannot be run as mortal. Try again as root"
	exit 1
fi


echo -e " [${GRN}+${NC}] disable PING requests"
grep -q "net.ipv4.icmp_echo -e_ignore_all = 1" /etc/sysctl.conf
if [ $? != 0 ] ;
then
	echo -e "#Ignore ICMP request:
net.ipv4.icmp_echo -e_ignore_all = 1" >> /etc/sysctl.conf
else
	echo -e " [${E}✘${NC}] this parameter already exist"
fi

echo -e " [${GRN}+${NC}] disable BROADCAST requests"
grep -q "net.ipv4 .icmp_echo -e_ignore_broadcasts = 1" /etc/sysctl.conf
if [ $? != 0 ] ;
then
	echo -e "#Ignore Broadcast request:
net.ipv4 .icmp_echo -e_ignore_broadcasts = 1" >> /etc/sysctl.conf
else
	echo -e " [${E}✘${NC}] this parameter already exist"
fi

echo -e " [${GRN}+${NC}] change /boot permissions to read only"
sed -i 's/0       2/1       2/g' /etc/fstab
