#!/bin/bash

GRN='\033[0;32m'
RED='\033[0;31m'
BLU='\033[1;34m'
NC='\033[0m'
A='\033[0;34m'
B='\033[0;31m'
C='\033[0;32m'
D='\033[0;33m'
E='\033[0;34m'
F='\033[0;35m'
G='\033[0;36m'
H='\033[0;28m'
I='\033[2;33m'
J='\033[3;31m'


if [[ $EUID -ne 0 ]];
then
	echo -e " [${RED}!${NC}] I cannot be run as mortal. Try again as root"
	exit 1
fi

printf  " [${BLU}?${NC}] Do you want to disable IPv6 ? (yes/no)   "
read asw
if [ $asw == "yes" ] ;
then
	echo -e " [${GRN}+${NC}] disable IPv6"
	grep -q "net.ipv6.conf.all.disable_ipv6 = 1" /etc/sysctl.conf
	if [ $? != 0 ] ;
	then
		echo -e "
net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
	else
	echo -e " [${E}✘${NC}] this parameter already exist"
	fi
fi
