#!/bin/bash

GRN='\033[0;32m'
RED='\033[0;31m'
BLU='\033[1;34m'
NC='\033[0m'
A='\033[0;34m'
B='\033[0;31m'
C='\033[0;32m'
D='\033[0;33m'
E='\033[0;34m'
F='\033[0;35m'
G='\033[0;36m'
H='\033[0;28m'
I='\033[2;33m'
J='\033[3;31m'


if [[ $EUID -ne 0 ]];
then
	echo -e " [${RED}!${NC}] I cannot be run as mortal. Try again as root"
	exit 1
fi

printf  " [${BLU}?${NC}] do you want to set your local variables ? (yes/no)   "
read asw
if [ $asw == "yes" ];
then
	printf " [${BLU}?${NC}] set en_US.UTF-8 ? (yes/no)   "
	read asw
	if [ $asw == "yes" ];
	then
		echo -e " [${GRN}+${NC}] setting en_US.UTF-8"
		locale-gen "en_US.UTF-8"
	fi
	printf " [${BLU}?${NC}] set fr_FR.UTF-8 ? (yes/no)   "
	read asw
	if [ $asw == "yes" ];
	then
		echo -e " [${GRN}+${NC}] setting fr_FR.UTF-8"
		locale-gen "fr_FR.UTF-8"
	fi
	printf " [${BLU}?${NC}] set en_GB.UTF-8 ? (yes/no)   "
	read asw
	if [ $asw == "yes" ];
	then
		echo -e " [${GRN}+${NC}] setting en_GB.UTF-8"
		locale-gen "en_GB.UTF-8"
	fi
	echo -e " [${RED}!${NC}] dpkg-reconfigure will open an interface.
     Please choose the locales you accept before
     (press a key to access to the interface)"
	read asw
	dpkg-reconfigure locales
fi
