#!/bin/bash

GRN='\033[0;32m'
RED='\033[0;31m'
BLU='\033[1;34m'
NC='\033[0m'


if [[ $EUID -ne 0 ]];
then
	echo -e " [${RED}!${NC}] I cannot be run as mortal. Try again as root"
	exit 1
fi

echo -e " [${GRN}+${NC}] change ROOT password"
passwd $USER

printf " [${BLU}?${NC}] Are you on a Raspberry pi ? (yes/no)  "
read asw
if [ $asw == "yes" ] ;
then
	echo -e " [${GRN}+${NC}] change PI password"
	passwd pi
fi
